### ISSUE TITLE
关于新人的一点发展疑惑

### ISSUE THREAD

**Issue by freeNuomi** [FiYHer/handle_grant_access#2]
楼主你好,有幸看到你的视频教程,我觉得录制的非常棒,但是我在接下来的学习中发现,关于找基值比较困难,我是否有必要把汇编语言学完(大部分mmorpg都是od找的数据),还是说继续深入c++内核和驱动呢?目前比较疑惑,希望楼主有空能解答一下,万分感谢

**Comment by LittleNoobLol** [comment]
谢谢你的回答,我经过几个月的学习,现在把汇编,3环编程,pe,常用注入学完了,准备学习内核和驱动了.我遇到了个小问题,不知道怎么解决,不知道楼主你知不知道怎么处理.网站(https://dumps.host/),这个网站会提

**Comment by LittleNoobLol** [comment]
谢谢楼主的回答，我经过几个月的学习,把汇编,常用的三环编程，pe,常用注入,等基础知识学完了.

现在准备进军内核和驱动了,不过我最近遇到个小问题不知道怎么处理,不知道楼主有没有这方面的资料可以参考一下.

主要是关于游戏基址偏移的问题,我发现个网站:https://dumps.host/  这个网站会提供游戏的基址,但是我不知道怎么使用它们,我只知道像ue4的引擎会有GNames,GObjects,GWorld等,但是他们之间的关系我却完全不清楚,比如何如从GWorld读内存到人物的hp.

我是需要去学习游戏引擎知识吗,还是说别的东西?

**Comment by freeNuomi** [comment]
谢谢楼主的回答，我经过这几个月的学习，把汇编，常用的三环编程,pe文件，常用注入，等基础知识学完了。

现在正准备内核和驱动了，不过我最近遇到了这件小事，不知道怎么处理，不知道楼主有没有什么方面的资料可以参考一下。

主要是关于游戏基址偏移的问题：https://dumps.host/这个网站怎么会提供游戏的基址，但我不知道如何使用它们，我只知道UE4的引擎有GNames、GObjects、GWorld等基址,但是他们之间的关系我却完全不了解，比如何如从GWorld一层一层的读取内存到人物的HP。

我是需要去学习游戏引擎知识吗，还是说别的东西？
